"""
Terminal & Markdown Reporter for AI-DevPulse
"""

import os
from datetime import datetime, timezone
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn

console = Console()

def print_audit_summary(results):
    """Prints a beautiful Rich terminal table of audit results."""
    table = Table(title="⚡ AI-DevPulse Codebase Audit Summary", header_style="bold magenta")
    table.add_column("File Path", style="cyan", no_wrap=True)
    table.add_column("Health Score", style="green", justify="center")
    table.add_column("Key Audit Findings & Vulnerabilities", style="white")

    total_score = 0
    count = len(results)

    for res in results:
        file_name = res.get("file", "Unknown")
        score = res.get("score", 10.0)
        issues = res.get("issues", [])
        
        total_score += score
        score_str = f"{score:.1f}/10"
        score_style = "green" if score >= 8.0 else ("yellow" if score >= 6.0 else "bold red")

        issues_summary = "\n".join([f"• {i}" for i in issues[:3]])
        if len(issues) > 3:
            issues_summary += f"\n• ... and {len(issues) - 3} more issues"

        table.add_row(file_name, f"[{score_style}]{score_str}[/{score_style}]", issues_summary)

    avg_score = (total_score / count) if count > 0 else 10.0
    console.print(table)
    
    panel_color = "green" if avg_score >= 8.0 else "bold red"
    console.print(Panel(
        f"📊 [bold]Overall Codebase Quality Index:[/bold] [{panel_color}]{avg_score:.1f} / 10.0[/{panel_color}]\n"
        f"📁 Total Files Audited: [cyan]{count}[/cyan]",
        title="[bold yellow]Audit Complete[/bold yellow]",
        border_style="blue"
    ))

def generate_markdown_report(results, output_path="DEVPULSE_REPORT.md"):
    """Generates a comprehensive Markdown report file."""
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    total_score = sum(r.get("score", 10.0) for r in results)
    avg_score = (total_score / len(results)) if results else 10.0

    lines = [
        "# ⚡ AI-DevPulse Audit & Refactoring Report",
        f"Automated Code Review, Vulnerability Scan & Refactoring Analysis.",
        f"\n**Timestamp:** `{now_utc}`  ",
        f"**Overall Quality Score:** `{avg_score:.1f} / 10.0`  ",
        f"**Files Audited:** `{len(results)}`",
        "\n---",
        "## 📊 Code Health Breakdown\n",
        "| File | Score | Findings / Vulnerabilities |",
        "| :--- | :---: | :--- |"
    ]

    for r in results:
        file_name = r.get("file", "Unknown")
        score = r.get("score", 10.0)
        issues = r.get("issues", [])
        issues_str = "<br>".join([f"• {i}" for i in issues])
        lines.append(f"| `{file_name}` | **`{score:.1f}`** | {issues_str} |")

    lines.extend([
        "\n---",
        "### 🛡️ Recommended Security Actions",
        "1. Fix any hardcoded API secrets or credentials.",
        "2. Ensure all user inputs in subprocess / database calls are sanitized.",
        "3. Address performance bottlenecks and code duplication.",
        "\n*Generated by AI-DevPulse Autonomous CLI Agent.*"
    ])

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    console.print(f"[bold green]✓ Markdown report exported to {output_path}[/bold green]")
